version: "3"
services:
  epusdt:
    #image:  baicailin/epusdt
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile_alpine
    #command: /app/api_client_linux -c=/app/conf/config.yaml
    volumes:
      - ./env:/app/.env
    ports:
      - "8088:8000"
